//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMag.Validation.Web.ServicoInscricao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoInscricao.IInscricao")]
    public interface IInscricao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscricao/ValidarAcessoInscricao", ReplyAction="http://tempuri.org/IInscricao/ValidarAcessoInscricaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WCF.ValidationFault), Action="http://tempuri.org/IInscricao/ValidarAcessoInscricaoValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        bool ValidarAcessoInscricao(NetMag.Validation.WCF.Funcionario funcionario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInscricaoChannel : NetMag.Validation.Web.ServicoInscricao.IInscricao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InscricaoClient : System.ServiceModel.ClientBase<NetMag.Validation.Web.ServicoInscricao.IInscricao>, NetMag.Validation.Web.ServicoInscricao.IInscricao {
        
        public InscricaoClient() {
        }
        
        public InscricaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InscricaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscricaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscricaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarAcessoInscricao(NetMag.Validation.WCF.Funcionario funcionario) {
            return base.Channel.ValidarAcessoInscricao(funcionario);
        }
    }
}
